# Generated by Django 4.2.1 on 2023-06-16 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0002_song_allowed_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='allowed_emails',
        ),
        migrations.AddField(
            model_name='song',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
