# Generated by Django 4.2.1 on 2023-06-16 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_app', '0003_remove_song_allowed_emails_song_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
